<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <IsPackable>false</IsPackable>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../bin/Content.Server.Custom</OutputPath>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>false</WarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <Import Project="..\Directory.Packages.props" />
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\RobustToolbox\RobustToolbox.csproj" />
    <ProjectReference Include="..\Content.Shared\Content.Shared.csproj" />
    <ProjectReference Include="..\Content.Server\Content.Server.csproj" />
  </ItemGroup>
</Project>